// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYh1GBBfqaybfnnDi0LJbRh9F0HFFIXYU',
    appId: '1:973335419103:web:75e1f5f4df4cb9f6acb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    authDomain: 'bookapp-73219.firebaseapp.com',
    storageBucket: 'bookapp-73219.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASmm4ttcUVVGJdQoEJQHmMxAAqYTe3BIs',
    appId: '1:973335419103:android:baaafe15e47b36a4acb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    storageBucket: 'bookapp-73219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0Ys6EUEcnZwoTMNGuXbMzUZojJOVFNg',
    appId: '1:973335419103:ios:54f75bb76e712e8dacb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    storageBucket: 'bookapp-73219.appspot.com',
    androidClientId: '973335419103-om9h1ka65f0dpqvork25oianpuo2gl7e.apps.googleusercontent.com',
    iosClientId: '973335419103-8i2t9qpenr21ctm0kdk37a4ndbgfo2l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0Ys6EUEcnZwoTMNGuXbMzUZojJOVFNg',
    appId: '1:973335419103:ios:54f75bb76e712e8dacb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    storageBucket: 'bookapp-73219.appspot.com',
    androidClientId: '973335419103-om9h1ka65f0dpqvork25oianpuo2gl7e.apps.googleusercontent.com',
    iosClientId: '973335419103-8i2t9qpenr21ctm0kdk37a4ndbgfo2l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );
}
